_wandb:
    value:
        cli_version: 0.22.3
        e:
            lhlt7uh6t21fvw3xz0xxq99onc5tog8s:
                apple:
                    ecpuCores: 4
                    gpuCores: 10
                    memoryGb: 16
                    name: Apple M3
                    pcpuCores: 4
                    ramTotalBytes: "17179869184"
                    swapTotalBytes: "4294967296"
                codePath: halfkp/train.py
                codePathLocal: halfkp/train.py
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "994662584320"
                        used: "770072047616"
                email: looey2005@gmail.com
                executable: /Users/lewis/diss/.venv/bin/python3
                git:
                    commit: 0d00e33f8cb0059ea53f2c3a416be59e942ba6f5
                    remote: https://github.com/lewis-carson/dissertation.git
                host: Lewiss-MacBook-Pro-2.local
                memory:
                    total: "17179869184"
                os: macOS-15.5-arm64-arm-64bit-Mach-O
                program: /Users/lewis/diss/halfkp/train.py
                python: CPython 3.13.7
                root: /Users/lewis/diss
                startedAt: "2025-11-06T15:29:39.194325Z"
                writerId: lhlt7uh6t21fvw3xz0xxq99onc5tog8s
        m: []
        python_version: 3.13.7
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 16
            "4": 3.13.7
            "5": 0.22.3
            "12": 0.22.3
            "13": darwin-arm64
batch_size:
    value: 256
binpack_cache_dir:
    value: /Users/lewis/diss/data/_binpack_csv
binpack_converter:
    value: null
data_dir:
    value: /Users/lewis/diss/data
data_effective_dir:
    value: /Users/lewis/diss/data/_binpack_csv
data_format:
    value: binpack
device:
    value: mps
end_lambda:
    value: 0.75
epoch_size:
    value: 100000000
gamma:
    value: 0.992
learning_rate:
    value: 0.000875
network_save_period:
    value: 10
num_csv_files:
    value: 1
num_epochs:
    value: 600
num_workers:
    value: 4
random_fen_skipping:
    value: 3
start_lambda:
    value: 1
streaming:
    value: true
threads:
    value: 2
validation_size:
    value: 1000000
