_wandb:
    value:
        cli_version: 0.22.3
        e:
            0hick67154ydf37blwrua71lx9jt86m6:
                apple:
                    ecpuCores: 4
                    gpuCores: 10
                    memoryGb: 16
                    name: Apple M3
                    pcpuCores: 4
                    ramTotalBytes: "17179869184"
                    swapTotalBytes: "6442450944"
                args:
                    - /Users/lewis/diss/data/data-test80-csv
                codePath: halfkp/train.py
                codePathLocal: train.py
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "994662584320"
                        used: "767931916288"
                email: looey2005@gmail.com
                executable: /Users/lewis/diss/.venv/bin/python
                git:
                    commit: e258e338765a454665e2fefa2df89233e480dc41
                host: Lewiss-MacBook-Pro-2.local
                memory:
                    total: "17179869184"
                os: macOS-15.5-arm64-arm-64bit-Mach-O
                program: /Users/lewis/diss/halfkp/train.py
                python: CPython 3.13.7
                root: /Users/lewis/diss/halfkp
                startedAt: "2025-11-06T12:33:37.912526Z"
                writerId: 0hick67154ydf37blwrua71lx9jt86m6
        m: []
        python_version: 3.13.7
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 16
            "4": 3.13.7
            "5": 0.22.3
            "12": 0.22.3
            "13": darwin-arm64
batch_size:
    value: 256
data_dir:
    value: /Users/lewis/diss/data/data-test80-csv
device:
    value: mps
end_lambda:
    value: 0.75
epoch_size:
    value: 100000000
gamma:
    value: 0.992
learning_rate:
    value: 0.000875
network_save_period:
    value: 10
num_csv_files:
    value: 29
num_epochs:
    value: 600
num_workers:
    value: 4
random_fen_skipping:
    value: 3
start_lambda:
    value: 1
streaming:
    value: true
threads:
    value: 2
validation_size:
    value: 1000000
