_wandb:
    value:
        cli_version: 0.22.2
        e:
            175u08xoj9deapwlwi2h0wqph74ggkgb:
                apple:
                    ecpuCores: 4
                    gpuCores: 10
                    memoryGb: 16
                    name: Apple M3
                    pcpuCores: 4
                    ramTotalBytes: "17179869184"
                    swapTotalBytes: "5368709120"
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "994662584320"
                        used: "539848159232"
                email: looey2005@gmail.com
                executable: /opt/homebrew/opt/python@3.11/bin/python3.11
                host: Lewiss-MacBook-Pro.local
                memory:
                    total: "17179869184"
                os: macOS-15.5-arm64-arm-64bit
                program: /Users/lewis/disschess/halfkp/train.py
                python: CPython 3.11.12
                root: /Users/lewis/disschess/halfkp
                startedAt: "2025-10-15T13:35:10.597607Z"
                writerId: 175u08xoj9deapwlwi2h0wqph74ggkgb
        m: []
        python_version: 3.11.12
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 16
            "4": 3.11.12
            "5": 0.22.2
            "12": 0.22.2
            "13": darwin-arm64
batch_size:
    value: 16384
device:
    value: mps
end_lambda:
    value: 0.75
epoch_size:
    value: 100000000
gamma:
    value: 0.992
learning_rate:
    value: 0.000875
network_save_period:
    value: 10
num_csv_files:
    value: 1
num_epochs:
    value: 600
num_workers:
    value: 4
random_fen_skipping:
    value: 3
start_lambda:
    value: 1
streaming:
    value: true
threads:
    value: 2
validation_size:
    value: 1000000
