[package]
name = "binpack-reader"
version = "0.1.0"
edition = "2021"

[dependencies]
sfbinpack = { path = "../binpack" }
clap = { version = "4", features = ["derive"] }
csv = "1.3"
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
crossbeam-channel = "0.5"
num_cpus = "1.17"
